<footer> <!--Lachlan - Footer of website-->
        <div class="site_footer"> <!--Custom class for layout-->
            <div>
                <section>
                    <h3>Navigation</h3>
                    <a href="index.php">Main</a>
                    <a href="about.php">About us</a>
                    <a href="jobs.php">Jobs</a>
                    <a href="apply.php">Apply</a>
                    <a href="package.php">Packages</a>
                </section>
                <section>
                    <h3>Socials</h3>
                    <a href="https://youtube.com">Youtube</a>
                    <a href="https://discord.com">Discord</a>
                    <a href="https://snapchat.com">Snapchat</a>
                    <a href="https://instagram.com">Instagram</a>
                    <a href="https://tiktok.com">Tik Tok</a>
                </section>
                <section>
                    <h3>Contacts</h3>
                    <a href="">24/7 Hotline: 529822125</a>
                    <a href="mailto:info@vdls.com.au">info@vdls.com.au</a>
                    <a href="mailto:Matthew@vdls.com.au">Matthew@vdls.com.au</a>
                    <a href="mailto:Lachlan@company.com.au">Lachlan@vdls.com.au</a>
                    <a href="mailto:Marcus@company.com.au">Marcus@vdls.com.au</a>
                </section>
            </div>
            <br>
            <div class="site_footer_bottom">
                <!--Jira Project Link-->
               <a href="https://yeotzufeng.atlassian.net/jira/software/projects/SCRUM/boards/1">Jira Project</a>
               <a href="https://github.com/PeakFiction2006/Group-Project-">Github Repository</a>
               <!--Fake Copyright for asthetics-->
               <a class="site_footer_copyright">
                   (Not) @ 2025 Copyright Victoria Digital Security Services
               </a>
           </div>
        </div>
    </footer>
