<!-- Page template by Lachlan, modified by Marcus -->
<?php include("header.inc");?>
<head>
    <title>VDLS - Careers at VDLS</title>
    <meta name="description" content="Work under your corporate overlords in our currently open positions.">
</head>
<?php include("menu.inc");?>

<body>
    <!--Put all of the webpage content inside this div-->
    <!-- Note that semantic tags will replace div tags in the future - MA -->
    <div class="site_content jobs_background">
        
        
        <h1>Careers at Victoria Digital Security</h1>
        <p>We are currently looking to expand Victoria Digital Security. Positions that are currently open are listed below.</p>
   
    <aside id="jobs_disclaim_section">
        <div id="benefits">
            <h2><strong>Benefits at Victoria Digital Security</strong></h2>
            <p>At Victoria Digital Security, you will employee benefits, such as:</p>
            <br>
            All mandatory benefits in Victoria, including:
                <ul>
                    <li>4 weeks annual paid leave</li>
                    <li>Parental leave</li>
                    <li>Sick leave</li>
                    <li>Days off and/or increased pay on public holidays</li>
                    <li>Superannuation that is managed by us</li>
                    <li>Workers' Compensation Insurance</li>                    
                </ul>
                Standard workplace benefits, including:
                <ul>
                    <li>Flexible work arrangements, such as flexible hours and working from home</li>
                    <li>Employee training and development</li>
                    <li>Career progression opportunities, such as promotions</li>
                    <li>Medical and mental wellbeing programs, such as mental health support and wellbeing programs</li>
                    <li>Team-building and social exercises</li>
                </ul>
                Additional workplace benefits
                <ul>
                    <li>Ergenomic workstations to support our employees</li>
                    <li>Communal facilities</li>
                </ul>
                <br>
            <!-- All beneifts generated by ChatGPT
             Prompt: "what kind of benefits do typical office workplaces offer?"
             Date: 13/04/2025 -->
        </div>
        <div id="notesdisclaimers">
            <h2><strong>Notes and Disclaimers</strong></h2>
            <p>Equal Opportunity Employer Statement</p>
            <ul>
                <li><em>We are an Equal Opportunity Employer and are committed to fostering a diverse and inclusive workplace. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity or expression, age, disability, marital status, family responsibilities, political belief, national origin, or any other characteristic protected under applicable equal opportunity laws.</em></li>
                <!-- Equal Opportunity Statement generated by ChatGPT
                Prompt: "write a disclaimer according to the equal opportunity act"
                Date: 11/04/2025 -->
            </ul>            
            <ul>
                <li>Preferable requirements are not exhaustive and we may or may not look for more skills/qualities that are not listed under the job listings. Think of them as "nice to haves".</li>
                <li>Responsibilities and tasks listed under job listings are not exhaustive, and you may be requierd to perform job functions beyond those described.</li>
                <!-- Job functions disclaimer made in reference to https://www.zippia.com/employer/how-to-write-a-job-description/ -->
            </ul>            
        </div>        
    </aside>

    <br><br>

    <div id="jobs_positions">  <!-- Seperate div for listed positions -->
    <h2>Open Positions at Careers at Victoria Digital Security</h2>            
                <div id="network_admin">  <!-- Seperate div for Network Admin -->
                    <section>
                        <h3>Network Administrator</h3>
                            <p>Reference Number: NAXG2</p> <!-- Alphanumeric code for job -->
                            <p>Salary: $85,00 - $105,000 AUD (<a href="https://www.seek.com.au/career-advice/role/network-administrator/salary" target="_blank">source</a>)</p> <!-- Source provided -->
                            <p>Years of experience: MINIMUM 2 years</p>
                            <!-- Years of experience generated by ChatGPT.
                            Prompt: "when hiring a systems engineer, what is the minimum years of experience I should look for", "what about network administrator?"
                            Date (DD/MM/YYYY): 10/04/2025 -->                        
                        <h4>Brief Description</h4>
                        <p>We're looking for a proactive and detail-oriented Network Administrator to join our IT team.
                        In this role, you'll be responsible for managing and maintaining our network infrastructure, ensuring the security, performance, and reliability of systems that support our day-to-day operations.
                        </p>
                        <!-- Description was generated by ChatGPT
                        Prompts: "what are some "essential" and "preferable" qualifications, skills, knowledge and attributes for network administrator?", "job ad"
                        Date (DD/MM/YYYY): 10/04/2025 -->
                        <h4>Responsibilities of a Network Administrator at CORPORATION</h4>
                                <ol>
                                    <li>Network Installation and Configuration
                                        <ul>
                                            <li>Set up and configure routers, switches, firewalls, and wireless access points</li>
                                            <li>Install and maintain networking software and hardware</li>                                                
                                        </ul>
                                        <br>
                                    </li>                                        
                                    <li>Monitoring and Performance Management
                                        <ul>
                                            <li>Continuously monitor network performance</li>
                                            <li>Use tools like SolarWinds, Nagios, or Wireshark to identify issues</li>
                                            <li>Ensure uptime and optimize speed and efficiency of the network</li>                                        
                                        </ul>
                                        <br>
                                    </li>                                   
                                        <li>Troubleshooting and Support
                                            <ul>
                                                <li>Respond to network outages and technical issues</li>
                                                <li>Provide support to end-users experiencing connectivity problems</li>
                                                <li>Diagnose and resolve hardware, software, and connectivity issues</li>                                                
                                            </ul>
                                            <br>
                                        </li>
                                        <li>Security Management
                                            <ul>
                                                <li>Implement firewalls and security protocols</li>
                                                <li>Manage antivirus, access controls, and VPN configurations</li>                          
                                                <li>Perform regular security audits and updates to guard against breaches</li>
                                               </ul>
                                               <br>
                                        </li>                                        
                                        <li>User Account and Access Control
                                            <ul>
                                                <li>Manage permissions, access rights, and user accounts</li>
                                                <li>Monitor network usage to prevent unauthorized access or misuse</li>                                                
                                            </ul>
                                        </li>                                        
                                        <li>Network Documentation and Reporting
                                        <ul>
                                            <li>Maintain accurate documentation of configurations and procedures</li>
                                            <li>Track inventory of hardware and licenses</li>
                                            <li>Generate performance and incident reports for management</li>                                            
                                            </ul>
                                            <br>
                                        </li>                                        
                                        <li>Data Backup and Recovery
                                            <ul>
                                                <li>Ensure regular backups of network configurations and critical data</li>
                                                <li>Create and test disaster recovery plans</li>
                                            </ul>
                                            <br>
                                        </li>                                        
                                        <li>Upgrades and Maintenance                                        
                                            <ul>
                                                <li>Install patches, updates, and firmware</li>
                                                <li>Recommend and implement hardware/software upgrades</li>
                                                <li>Plan and test new networking technologies</li>
                                                </ul>
                                                <br>
                                        </li>                                        
                                        <li>Collaboration and Training                                        
                                            <ul>
                                                <li>Work with IT teams, vendors, and service providers</li>
                                                <li>Train staff on basic networking tools and safety practices</li>
                                            </ul>
                                            <br>
                                        </li>                                        
                                        <li>Compliance and Best Practices
                                            <ul>
                                                <li>Ensure the network complies with organizational policies and industry standards (e.g., ISO, HIPAA, GDPR depending on industry)</li>
                                            </ul>
                                            <br>
                                        </li>              
                                </ol>                            
                            <!-- Responsibilities generated by ChatGPT
                            Prompts: "what are some things/responsibilites of a network admin"
                            Date (DD/MM/YYYY): 10/04/2025 -->    
                        <h4>Key Network Administrator Skills</h4>
                            <ul>
                                <li>Knowledge of different types of networks: Network types include Local Area Networks (LANs), Wide Area Networks(WANs), Virtual Private Networks (VPNs), and sometimes Storage Area Networks (SANs). 
                                    Though some jobs may require more experience in one over another, having a basic understanding of the various network types and how to configure them will be crucial to your network administrator skill set.
                                </li>

                                <li>Understanding of network security components: These include firewalls, VPNs, and access control. 
                                    Knowing about common cyber attacks and the appropriate response to them is critical for a network administrator.
                                </li>
                                    
                                <li>Familiarity with servers: Upgrading and configuring servers is a sought-after skill for network administrators. These may include Windows and Linux operating systems.
                                </li>
                                <li>Communication and teamwork: As a network administrator, you'll likely work on a team or with other organization members to ensure computers and systems are running smoothly. 
                                    Being able to communicate problems and solutions with other people is a valuable skill to have.
                                </li>
                                <!-- Skills and Requriements taken from https://www.coursera.org/articles/what-is-a-network-administrator-a-career-guide -->
                            </ul>
                        <h4>Essential Qualifications and Skills</h4>                        
                            <ul>
                                <li>Degree in Information Technology, Computer Science, or related field</li>                    
                                <li>1-3 years of experience in a network administration or support role</li>                    
                                <li>Strong understanding of TCP/IP, LAN/WAN, DNS, DHCP, and VPN</li>                    
                                <li>Experience with network hardware (e.g., Cisco, HP, Ubiquiti)</li>                    
                                <li>Familiarity with Windows Server and/or Linux environments</li>                                        
                                <li>Strong analytical and communication skills</li>
                                <li>Ability to work independently and prioritize tasks effectively</li>
                                <!-- Essential Qualifications and Skills generated by ChatGPT.
                                Prompts: "what are some "essential" and "preferable" qualifications, skills, knowledge and attributes for network administrator?", "job ad"
                                Date (DD/MM/YYYY): 10/04/2025 -->
                            </ul>                        
                        <h4>Preferable Qualifications and Skills</h4>                        
                            <ul>
                                <li>Bachelor's degree (if not already required)</li>
                                <li>Certifications: CompTIA Network+ or CCNA</li>
                                <li>Additional certifications: CCNP, Microsoft Certified: Azure Administrator, or similar</li>
                                <li>Experience with cloud platforms (AWS, Azure, Google Cloud)</li>
                                <li>Knowledge of virtualization (VMware, Hyper-V)</li>
                                <li>Familiarity with network monitoring tools (e.g., SolarWinds, Wireshark)</li>
                                <li>Scripting knowledge (PowerShell, Bash)</li>
                                <li>Exposure to ITIL, Agile, or project management practices</li>
                                <!-- Preferable Qualifications and Skills generated by ChatGPT.
                                Prompts: "what are some "essential" and "preferable" qualifications, skills, knowledge and attributes for network administrator?", "job ad"
                                Date (DD/MM/YYYY): 10/04/2025 -->
                            </ul>
                        
                            <br><br>
                        
                        <h3>On successful appliance, you will report directly to Matthew Yeo.</h3>
                        <h3>Finished Reading? Apply <a href="apply.html">Here.</a></h3>
                     
                    </section>
                </div>
                
                <br><br><br>                

                    <section id="systems_engineer"> <!-- Seperate section for Systems Engineer -->
                        
                        <h3>Systems Engineer</h3> <!-- Thought of a random job, thought of Dead Space's Isaac Clarke - Systems Engineer -->
                                <p>Reference Number: SE7M5</p>
                                <p>Salary: $100,000 - $130,000 AUD (<a href="https://www.randstad.com.au/job-profiles/systems-engineer/" target="_blank">source</a>)</p>
                                <p>Years of experience: MINIMUM 3 years</p> 
                                <!-- Years of experience generated by ChatGPT 
                                Prompt: "when hiring a systems engineer, what is the minimum years of experience I should look for" 
                                Date (DD/MM/YYYY):10/04/2025 -->
                                <h4>Brief Description</h4>
                                    <p>A systems engineer is a professional who applies engineering principles to develop and maintain efficient systems.</p>
                                    <p>They play a crucial role in various industries by solving problems in systems.</p>
                                    <p>Unlike other engineers who solve issues in independent parts, a systems engineer takes a holistic approach by studying the interconnections of systems.</p>
                                    <p>When a systems engineer develops a system, they ensure it provides a positive user experience while considering the company objectives and operations.</p>
                                    <!-- Description taken from https://www.randstad.com.au/job-profiles/systems-engineer/ -->                                
                                <h4>Responsibilities of a Systems Engineer at CORPORATION</h4> <!-- Credit/reference at the end of this content -->
                                    <ol>
                                            <li>System Design and Architecture
                                                <ul>
                                                    <li>Analyze user and business requirements to design scalable systems</li>
                                                    <li>Develop system architecture and specifications for hardware and software</li>
                                                    <li>Create system models, diagrams, and documentation</li>                                                    
                                                </ul>
                                                <br>
                                            </li>                                            
                                            <li>System Integration                                            
                                                <ul>
                                                    <li>Integrate hardware, software, and network components into a cohesive system</li>
                                                    <li>Ensure compatibility across platforms and technologies</li>
                                                    <li>Coordinate with vendors and developers to support integration tasks</li>                                                   
                                                </ul>
                                                <br>
                                            </li>                                             
                                            <li>Installation, Configuration, and Deployment                                            
                                                <ul>
                                                    <li>Install and configure operating systems, servers, and system applications</li>
                                                    <li>Deploy solutions in line with project requirements and timelines</li>
                                                    <li>Ensure systems are set up according to organizational standards</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                            <li>Monitoring and Maintenance
                                                <ul>
                                                    <li>Monitor system performance and availability</li>
                                                    <li>Perform regular maintenance and updates to ensure   reliability</li>
                                                    <li>Tune systems to enhance performance and reduce downtime</li>
                                                </ul>
                                                <br>
                                            </li>                                           
                                            <li>Troubleshooting and Issue Resolution
                                                <ul>
                                                    <li>Diagnose system-related issues and identify root causes</li>
                                                    <li>Implement fixes and recommend permanent solutions</li>
                                                    <li>Support users and technical staff in resolving escalated issues</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                            <li>Security and Compliance
                                                <ul>
                                                    <li>Implement security measures like firewalls, access controls, and encryption</li>
                                                    <li>Ensure systems comply with internal policies and external regulations (e.g., ISO, NIST)</li>
                                                    <li>Regularly patch vulnerabilities and perform risk assessments</li>
                                                </ul>
                                                <br>
                                            </li>
                                            <li>Documentation and Reporting
                                                <ul>
                                                    <li>Document configurations, procedures, and system architectures</li>
                                                    <li>Maintain records of system updates, incidents, and changes</li>
                                                    <li>Prepare reports for audits, reviews, and internal tracking</li>
                                                </ul>
                                                <br>
                                            </li>
                                            <li>Automation and Optimization
                                                <ul>
                                                    <li>Use scripting tools (e.g., PowerShell, Python) to automate system tasks</li>
                                                    <li>Improve existing processes to boost system efficiency and reliability</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                            <li>Project Participation and Collaboration
                                                <ul>
                                                    <li>Collaborate with developers, IT teams, and stakeholders on projects</li>
                                                    <li>Contribute to the planning and implementation of infrastructure upgrades</li>
                                                    <li>Support Agile or DevOps methodologies as applicable</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                            <li>Continuous Improvement and Learning
                                                <ul>
                                                    <li>Stay current with emerging technologies and best practices</li>
                                                    <li>Evaluate new tools and platforms for potential use</li>
                                                    <li>Participate in training, certifications, and professional development</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                        </ol>
                                                                      
                                
                                <!-- Responsibilities generated by ChatGPT
                                 Prompts: "what are some things/responsibilites of a network admin", "what about systems engineer? format it the same way as the previous response" 
                                 Dates: 10/04/2025, 11/04/2025 -->
    
                                <h4>Key Systems Engineer Skills and Requirements</h4>
                                
                                    <ul> 
                                        <li>Problem-Solving and Critical Thinking: Developing innovative solutions to complex challenges by analyzing systems holistically.</li>
                                                              
                                        <li>Effective Communication: Clearly conveying technical information to diverse stakeholders, facilitating collaboration and ensuring project alignment.</li>
                                                          
                                        <li>Time Management and Prioritization: Balancing multiple projects and deadlines efficiently to maintain productivity.</li>
                                              
                                        <li>Adaptability and Flexibility: Adjusting to evolving technologies and project requirements in a dynamic environment.</li>
                                        
                                        <li>Systems Architecture Design and Modeling: Creating and analyzing system structures to ensure they meet functional and performance requirements. </li>   
                                                          
                                        <li>Programming and Scripting Languages: Proficiency in languages such as Python, Java, or C++ for system development and automation.</li>
                                        
                                        <li>Network Configuration and Security: Understanding network protocols and implementing security measures to protect system integrity.</li>
                                              
                                        <li>Cloud Infrastructure and Services: Experience with cloud platforms and services to design scalable and reliable systems.</li>     
                                        
                                        <li>Automation and Orchestration Tools: Utilizing tools to automate system processes and improve efficiency.</li>      
                                                  
                                        <li>Continuous Learning: Staying updated with technological advancements to incorporate new solutions and maintain system relevance.</li>
                                        <!-- Skills and Requirements generated by ChatGPT
                                        Prompt: "What are some key skills of a systems engineer"
                                        Date (DD/MM/YYYY): 10/04/2025 -->
                                    </ul> 
                                
                                <!-- Credit given at end of this content -->
                                <h4>Essential Qualifications and Skills</h4>                                    
                                        <ul>
                                            <li>Bachelor's degree in Systems Engineering, Computer Science, Information Technology, or related field</li>
                                            <li>Relevant certifications (one or more of):
                                                <ul>
                                                    <li>Microsoft Certified: Azure Administrator Associate</li>
                                                    <li>Red Hat Certified System Administrator (RHCSA)</li>
                                                    <li>CompTIA Server+, Linux+, or similar</li>
                                                </ul>
                                                <br>
                                            </li>                                                
                                            <li>Technical Skills:
                                                <ul>
                                                    <li>Experience with system installation, configuration, and maintenance (Windows, Linux, or both)</li>
                                                    <li>Understanding of networking fundamentals, storage systems, and cloud infrastructure</li>
                                                    <li>Proficiency in scripting languages (e.g., PowerShell, Bash, Python)</li>
                                                    <li>Ability to diagnose and troubleshoot hardware/software/system issues</li>
                                                    <li>Familiarity with virtualization technologies (e.g., VMware, Hyper-V)</li>
                                                </ul>
                                                <br>
                                            </li>                                                
                                            <li>Soft Skills:
                                                <ul>
                                                    <li>Strong problem-solving and analytical thinking</li>
                                                    <li>Excellent communication and documentation skills</li>
                                                    <li>Ability to work collaboratively across teams</li>
                                                    <li>Organized, with good time management skills</li>
                                                </ul>
                                                <br>
                                            </li>                                                
                                        </ul>                                    
                                    <h4>Preferable Qualifications and Skills</h4>
                                    
                                        <ul>
                                            <li>Qualifications:
                                                <ul>
                                                    <li>Master's degree in a related field
                                                    </li>
                                                </ul>
                                                <br>
                                            </li>
                                            <li>Advanced certifications such as:                                            
                                                <ul>
                                                    <li>AWS Certified Solutions Architect - Associate/Professional</li>
                                                    <li>Certified Systems Engineering Professional (CSEP)</li>
                                                    <li>Cisco Certified Network Professional (CCNP)</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                            <li>Technical Skills:
                                                <ul>
                                                    <li>Experience with DevOps tools (e.g., Jenkins, Docker, Ansible)</li>
                                                    <li>Knowledge of cloud platforms (AWS, Azure, Google Cloud)</li>
                                                    <li>Background in cybersecurity practices</li>
                                                    <li>Familiarity with CI/CD pipelines and automation tools</li>
                                                    <li>Experience with enterprise architecture and system lifecycle management</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                            <li>Soft Skills:
                                                <ul>
                                                    <li>Project management skills or certifications (e.g., Agile, Scrum, PMP)</li>
                                                    <li>Leadership and mentoring capabilities</li>
                                                    <li>Strong attention to detail and system-level thinking</li>
                                                </ul>
                                                <br>
                                            </li>                                            
                                        </ul>
                                        <!-- Essential and Preferable Qualifications and skills generated by ChatGPT
                                        Prompt: 
                                        Date: 14/04/2025 -->                                                                           
                                    <br><br>                                
                            
                            <h3>On successful appliance, you will report directly to Marcus Au.</h3>
                            <h3>Finished Reading? Apply <a href="apply.html">Here.</a></h3>
                    </section>

                    <br><br><br>

                    <section id="security_analyst">  <!-- Seperate section for security analyst -->
                        <h3>Security Analyst</h3>
                        <p>Reference Number: SAH05</p> <!-- Alphanumeric code for job -->
                        <p>Salary: $95,000 - $145,000 AUD (<a href="https://au.talent.com/salary?job=cyber+security+analyst" target="_blank">source</a>)</p> <!-- Source provided -->
                        <p>Years of experience: MINIMUM 2 years</p>
                        <!-- Years of experience generated by ChatGPT.
                        Prompt: "when hiring a security analyst, what is the minimum years of experience I should look for"
                        Date (DD/MM/YYYY): 14/04/2025 -->                        
                        <h4>Brief Description</h4>
                        <p>
                            We're seeking a Security Analyst to monitor, detect, and respond to cybersecurity threats across our systems.
                            You'll be responsible for managing security tools, investigating incidents, and helping to maintain compliance with industry standards.
                            Ideal candidates have 1-3 years of experience, a relevant degree or certification (e.g., Security+ or CEH), and strong problem-solving skills.                        
                        </p>
                        <!-- Description was generated by ChatGPT
                        Prompts: "what are some "essential" and "preferable" qualifications, skills, knowledge and attributes for security analyst?", "job ad", "short description?"
                        Date (DD/MM/YYYY): 14/04/2025 -->
                        <h4>Responsibilities of a Security Analyst at Victoria Digital Security</h4>
                            <ol>
                                <li>Monitor and analyze security alerts from SIEM tools, firewalls, and intrusion detection systems.</li>          
    
                                <li>Investigate and respond to security incidents and breaches, including root cause analysis.</li>
    
                                <li>Conduct vulnerability assessments and support patch management efforts.</li>
    
                                <li>Maintain and update security policies, procedures, and incident response plans.</li>
    
                                <li>Collaborate with IT teams to ensure secure system configurations and access controls.</li>
    
                                <li>Track and report on emerging threats and recommend appropriate risk mitigation strategies.</li>
    
                                <li>Support security awareness training and educate staff on cybersecurity best practices.</li>
    
                                <li>Assist with compliance requirements (e.g., ISO 27001, GDPR, PCI-DSS) and internal audits.</li>
    
                                <li>Document incidents, investigations, and response actions for reporting and improvement.</li>
    
                                <li>Participate in threat intelligence sharing and stay updated on current threat landscapes.</li>
                            </ol>                            
                            <!-- Responsibilities generated by ChatGPT
                            Prompts: "what are some responsibilities of a security analyst? format it in the same 10 point list as the two previous jobs"
                            Date (DD/MM/YYYY): 14/04/2025 -->
                        <h4>Essential Qualifications and Skills</h4>                        
                            <ul>
                                <li>Bachelor's degree in Cybersecurity, IT, or related field</li>
                                <li>1-3 years of experience in a cybersecurity or IT security role</li>
                                <li>Experience with SIEM platforms (e.g., Splunk, QRadar), firewalls, and endpoint security tools</li>
                                <li>Solid understanding of network protocols, system hardening, and threat mitigation</li>
                                <li>Strong analytical, documentation, and communication skills</li>
                                <!-- Essential Qualifications and Skills generated by ChatGPT.
                                Prompts: "what are some "essential" and "preferable" qualifications, skills, knowledge and attributes for security analyst?", "job ad"
                                Date (DD/MM/YYYY): 14/04/2025 -->
                            </ul>
                        <h4>Preferable Qualifications and Skills</h4>
                            <ul>
                                <li>Experience with cloud security (AWS, Azure, or GCP)</li>
                                <li>Advanced certifications: CISSP, CISM, GCIH, or similar</li>
                                <li>Knowledge of compliance standards such as PCI-DSS, GDPR, or ISO 27001</li>
                                <li>Scripting or automation knowledge (e.g., Python, PowerShell)</li>
                                <li>Experience working in a Security Operations Centre (SOC)</li>
                                <!-- Preferable Qualifications and Skills generated by ChatGPT.
                                Prompts: "what are some "essential" and "preferable" qualifications, skills, knowledge and attributes for security analyst?", "job ad"
                                Date (DD/MM/YYYY): 14/04/2025 -->
                            </ul>                    
                            <br><br>                    
                        <h3>On successful appliance, you will report directly to Lachlan Phillips.</h3>
                        <h3>Finished Reading? Apply <a href="apply.html">Here.</a></h3>
                        </section>

                    <br>
            </div>
        </div>

<?php include("footer.inc");?>

</body>
</html>