<!-- Page template by Lachlan, modified by Marcus -->
<?php include("header.inc");?>
<head>
    <title>VDLS - Careers at VDLS</title>
    <meta name="description" content="Work under your corporate overlords in our currently open positions.">
</head>

<body>
<?php include("header.inc");?>
<?php include("menu.inc");?>

    <!--Put all of the webpage content inside this div-->
    <div class="site_content jobs_background">
        
        
        <h1>Careers at Victoria Digital Security</h1>
        <p>We are currently looking to expand Victoria Digital Security. Positions that are currently open are listed below.</p>
   
    <aside id="jobs_disclaim_section">
        <div id="benefits">
            <h2><strong>Benefits at Victoria Digital Security</strong></h2>
            <p>At Victoria Digital Security, you will employee benefits, such as:</p>
            <br>
            All mandatory benefits in Victoria, including:
                <ul>
                    <li>4 weeks annual paid leave</li>
                    <li>Parental leave</li>
                    <li>Sick leave</li>
                    <li>Days off and/or increased pay on public holidays</li>
                    <li>Superannuation that is managed by us</li>
                    <li>Workers' Compensation Insurance</li>                    
                </ul>
                Standard workplace benefits, including:
                <ul>
                    <li>Flexible work arrangements, such as flexible hours and working from home</li>
                    <li>Employee training and development</li>
                    <li>Career progression opportunities, such as promotions</li>
                    <li>Medical and mental wellbeing programs, such as mental health support and wellbeing programs</li>
                    <li>Team-building and social exercises</li>
                </ul>
                Additional workplace benefits
                <ul>
                    <li>Ergenomic workstations to support our employees</li>
                    <li>Communal facilities</li>
                </ul>
                <br>
            <!-- All beneifts generated by ChatGPT
             Prompt: "what kind of benefits do typical office workplaces offer?"
             Date: 13/04/2025 -->
        </div>
        <div id="notesdisclaimers">
            <h2><strong>Notes and Disclaimers</strong></h2>
            <p>Equal Opportunity Employer Statement</p>
            <ul>
                <li><em>We are an Equal Opportunity Employer and are committed to fostering a diverse and inclusive workplace. All qualified applicants will receive consideration for employment without regard to race, color, religion, sex, sexual orientation, gender identity or expression, age, disability, marital status, family responsibilities, political belief, national origin, or any other characteristic protected under applicable equal opportunity laws.</em></li>
                <!-- Equal Opportunity Statement generated by ChatGPT
                Prompt: "write a disclaimer according to the equal opportunity act"
                Date: 11/04/2025 -->
            </ul>            
            <ul>
                <li>Preferable requirements are not exhaustive and we may or may not look for more skills/qualities that are not listed under the job listings. Think of them as "nice to haves".</li>
                <li>Responsibilities and tasks listed under job listings are not exhaustive, and you may be requierd to perform job functions beyond those described.</li>
                <!-- Job functions disclaimer made in reference to https://www.zippia.com/employer/how-to-write-a-job-description/ -->
            </ul>            
        </div>        
    </aside>

    <br><br>

    <div id="jobs_positions">  <!-- Seperate div for listed positions -->
        <h2>Open Positions at Careers at Victoria Digital Security</h2>

        <section id="network_admin"> <!-- Section for Network Admin -->
            <?php // php start
                $conn = mysqli_conect($host, $username, $password, $database); // Connect to the job listings database
                if (!$conn) { // Check connection
                    echo "<p>Database connection failed: " . mysqli_connect_error() . "</p>";
                } else {
                    // Query to get job listing data
                    $sql = "SELECT *, description, picture FROM listings_basic";
                    $result = mysqli_query($conn, $sql);

                    if ($result && mysqli_num_rows($result) > 0) {
                        while ($row = mysqli_fetch_assoc($result)) {
                            //Output from database 
                        }
                    }

                }



            ?>
        </section>

                    
         
                <br><br><br>                

                    <section id="systems_engineer"> <!-- Section for Systems Engineer -->
                        
                    </section>

                    <br><br><br>

                    <section id="security_analyst">  <!-- Section for security analyst -->
                    
                </section>

                    <br>
    </div>

<?php include("footer.inc");?> <!-- Include the footer file -->

</body>
</html>