<div id="site_header"> <!--Lachlan - Top bar / "Header" of page-->
        <div class="site_header_item"> <!--Lachlan - Clickable logo to redirect to index.html-->
            <!--Logo source https://www.freeimages.com/vector/generic-logo-4846322-->
            <a href="index.php"><img src="../images/logo.png" class="site_header_company_logo" alt="The company logo"></a>
        </div>
        <div class="site_header_navbuttons"> <!--Lachlan - Buttons that show if the screen is large enough-->
            <a href="index.php">Home</a>
            <a href="about.php">About us</a>
            <a href="jobs.php">Jobs</a>
            <a href="apply.php">Apply</a>
            <a href="mailto:info@vdls.com.au">E-Mail</a> <!--Direct user to company email-->
        </div>
        <div class="site_menu_dropdown"> <!--Dropdown menu template from https://www.w3schools.com/howto/howto_css_dropdown.asp-->
            <button class="site_menu_dropdown_button"><img src="../images/menu.png" alt="Navigation Menu Icon" class="site_header_menu_image"></button>
            <!--Menu image sourced from https://icons8.com/icons/set/menu-->
            <div class="site_menu_dropdown_content"> <!--Drop down menu items to navigate site-->
              <a href="index.php">Home</a>
              <a href="about.php">About us</a>
              <a href="jobs.php">Jobs</a>
              <a href="apply.php">Apply</a>
              <a href="login.php">Login</a>
              <a href="mailto:info@vdls.com.au">E-Mail</a>  <!--Direct user to company email-->
            </div>
        </div>
    </div>